### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by getflourish** [AndrewKF/Sketch-Buttonsmith#1]
Hi there! I tried your plugin in 3.2 and I don’t get more than two lines of log message

```
( 10 ) <- padding input Buttonsmith.sketchplugin:55
( 0 ) <- radius input Buttonsmith.sketchplugin:56
15:52:25.264: Buttonsmith.sketchplugin - Script executed in 603 ms
```

What’s supposed to happen? :)

**Comment by AndrewKF** [comment]
What should be happening would be a rectangle object should be placed behind the layer currently selected and the corner radius would change on the value of the radius field. 

I'm working through a few bugs still on this plugin and still iterating on the UI for it. So it's still pretty deep in development.

Thanks for the heads up about 3.2 beta. I tried the plugin in the most recent version and, what limited functionality it has, is broken. I'll update the README.md to say this is still in the process of being developed.
